---
name: publish-dockerhub-description

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - DOCKERHUB_DESCRIPTION.md
      - .github/workflows/publish-dockerhub-description.yaml

env:
  SHORT_DESCRIPTION: GitHub actions workflow tests
  README_FILEPATH: ./DOCKERHUB_DESCRIPTION.md

jobs:
  dockerHubDescription:
    name: Publish description to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Publish description to Docker Hub
        uses: mrtwnklr/dockerhub-description@feat/convert_relative_urls_to_absolute
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          enable-url-completion: true
          image-extensions: bmp,gif,jpg,jpeg,png,svg,ico,webp
