---
name: publish-dockerhub-description

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - DOCKERHUB_DESCRIPTION.md
      - .github/workflows/publish-dockerhub-description.yaml

env:
  SHORT_DESCRIPTION: GitHub actions workflow tests
  README_FILEPATH: ./DOCKERHUB_DESCRIPTION.md

jobs:
  dockerHubDescription:
    name: Publish description to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Make relative urls absolute
        run: |
          sed -i -E 's#${{ env.README_RELATIVE_LINK_PATTERN }}#\1${{ env.README_ABSOLUTE_LINK_PREFIX }}\2#g' ${{ env.README_FILEPATH }}
          sed -i -E 's#${{ env.RAW_RELATIVE_LINK_PATTERN }}#\1${{ env.RAW_ABSOLUTE_LINK_PREFIX }}\2#g'       ${{ env.README_FILEPATH }}
          sed -i -E 's#${{ env.BLOB_RELATIVE_LINK_PATTERN }}#\1${{ env.BLOB_ABSOLUTE_LINK_PREFIX }}\2#g'     ${{ env.README_FILEPATH }}
        env:
          README_RELATIVE_LINK_PATTERN: (\[[^]]+\]\()(\#[^)]+\))
          README_ABSOLUTE_LINK_PREFIX: https://github.com/${{ github.repository }}/tree/${{ github.ref_name }}/${{ env.README_FILEPATH }}

          RAW_RELATIVE_LINK_PATTERN: (\[[^]]+\]\()([^:)]+[.](bmp|gif|jpg|jpeg|png|svg)\))
          RAW_ABSOLUTE_LINK_PREFIX: https://github.com/${{ github.repository }}/raw/${{ github.ref_name }}/

          BLOB_RELATIVE_LINK_PATTERN: (\[[^]]+\]\()([^:)]+\))
          BLOB_ABSOLUTE_LINK_PREFIX: https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/

      - name: Publish description to Docker Hub
        uses: peter-evans/dockerhub-description@067627a8af8c4a66c03b5b5e896968ca4cafba79
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
